[agent]
  interval = "1s"
  flush_interval = "5s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "power/+/measurements",
    "modbus/device/+/registers",
    "nidaq/+/snapshot",
  ]
  qos = 0
  persistent_session = true
  client_id = "telegraf_powermeter"
  data_format = "json_v2" # JSON V2 is more flexible and has better error messaging.
  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this" # root object
      timestamp_key = "timestamp"
      timestamp_format = "unix"
      excluded_keys = [] # all other keys are treated as key-value pairs in the data
      tags = ["device"] # treat "device" as a tag


[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "valve/write",
    "vsd1/write",
    "vsd2/write",
    "solver/output/#"
  ]
  data_format="value"
  data_type="float"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "supersecrettoken"
  organization = "lab"
  bucket = "data"
