[agent]
  interval = "1s"
  flush_interval = "5s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "power/+/measurements",
    "modbus/device/+/registers",
    "nidaq/+/snapshot",
  ]
  qos = 0
  persistent_session = true
  client_id = "telegraf_powermeter"
  data_format = "json_v2"
  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this" # root object
      timestamp_key = "timestamp"
      timestamp_format = "unix"
      excluded_keys = [] # all other keys are treated as key-value pairs in the data
      tags = ["device"] # treat "device" as a tag


[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "supersecrettoken"
  organization = "lab"
  bucket = "data"
