[agent]
  interval = "1s"
  flush_interval = "5s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "nidaq/+/snapshot"
  ]
  qos = 0
  persistent_session = true
  client_id = "telegraf"

  data_format = "json"
  json_time_key = "timestamp"
  json_time_format = "unix"

  json_string_fields = ["device"]

  tag_keys = ["device"]

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "supersecrettoken"
  organization = "lab"
  bucket = "nidaq"
